export const DBG = {
  ALIGN_ALL: 0,
  ALIGN_LINE: 0,
  C10E_INSPECT: 0,
  C6R_CTOR: 0,
  COLOR_CONSOLE: 0,
  DEEPL_ADAPTER: 0,
  DEEPL_MOCK: 0, // use mock-deepl
  DEEPL_MOCK_XLT: 0, // use mock translation
  DEEPL_TEST_API: 0, // test with live DeepL API ($$$)
  DEEPL_XLT: 0, // test live translation
  I6L_CONTAINS: 0,
  I6L_OVERLAPS: 0,
  K31_PEEK_MESSAGE: 0,
  K3A_CONNECT: 0,
  K3A_CREATE_TOPICS: 0,
  K3A_CTOR: 0,
  K3A_P6R_CTOR: 0,
  K3A_DESCRIBE_GROUPS: 0,
  K3A_DISCONNECT: 0,
  K3A_FETCH_OFFSETS: 0,
  K3A_GROUP_OF_ID: 0,
  K3A_MESSAGE_CLOCK: 0,
  K3A_R4R_RUNNING: 0,
  K3A_SEND: 0,
  K3A_TOPIC_OF_NAME: 0,
  K3A_R4R_START: 2,
  L2T_TO_STRING: 0,
  L7C_FETCH_LEGACY: 0,
  L7C_FETCH_LEGACY_SC: 0, // ignore test cache and use SC
  ML_DOC_VECTORS: 0, // 'mn8:3.4',
  MN8_MOHAN: 0,
  N8A: {
    R4R: {
      CTOR: 1,
      PROCESS: 2,
      START: 1,
      STOP: 1,
    },
    C3K: {
      CREATE: 1,
      CTOR: 1,
      NEXT: 1,
      GENERATOR: 3,
    },
    C6R: {
      CTOR: 2,
      RUN: 1,
      SUBSCRIBE: 1,
      PROCESS: 0,
    },
  },
  T3R_CTOR: 0,
  T3R_UPDATE: 0,
  T4S_CTOR: 0,
  T4S_EACH_MESSAGE: 0,
  T4S_ON_LIST: 0,
  T4S_START: 2,
  W7E_BOW_OF_TEXT: 0,
  WORD_MAP_TRANFORMER: 0,
};
