export const DBG = {
  ALIGN_ALL: 0,
  ALIGN_LINE: 0,
  L2T_TO_STRING: 0,
  C10E_INSPECT: 0,
  C6R_CTOR: 1,
  COLOR_CONSOLE: 0,
  I6L_CONTAINS: 0,
  I6L_OVERLAPS: 0,
  ML_DOC_VECTORS: 0, // 'mn8:3.4',
  MN8_MOHAN: 0,
  DEEPL_ADAPTER: 0,
  DEEPL_MOCK: 0, // use mock-deepl
  DEEPL_MOCK_XLT: 0, // use mock translation
  DEEPL_TEST_API: 0, // test with live DeepL API ($$$)
  DEEPL_XLT: 0, // test live translation
  K3A_CTOR: 0,
  K3A_CONNECT: 0,
  K3A_CREATE_TOPICS: 1,
  K3A_DESCRIBE_GROUPS: 0,
  K3A_TOPIC_OF_NAME: 0,
  K3A_FETCH_OFFSETS: 1,
  K3A_GROUP_OF_ID: 0,
  K31_PEEK_MESSAGE: 1,
  K3A_RUN: 1,
  K3A_RUN_ONCE: 1,
  K3A_SEND: 1,
  K3A_SUBSCRIBE: 1,
  K3A_DISCONNECT: 0,
  L7C_FETCH_LEGACY: 0,
  L7C_FETCH_LEGACY_SC: 0, // ignore test cache and use SC
  W7E_BOW_OF_TEXT: 0,
  WORD_MAP_TRANFORMER: 0,
};
